version: '3.8'

services:
  backend:
    image: fizzbuzzgamebackend
    build:
      context: ../fizzbuzz-game-backend/fizzbuzz-game-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/data/fizzbuzz.db
    volumes:
      - sqlite_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      retries: 5
      start_period: 10s

  frontend:
    image: fizzbuzzgamefrontend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://backend:8080
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_healthy

volumes:
  sqlite_data: