version: '3.8'

services:
  backend:
    image: fizzbuzzgamebackend
    build:
      context: ../fizzbuzz-game-backend/fizzbuzz-game-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/data/fizzbuzz.db
      - ASPNETCORE_URLS=http://0.0.0.0:8080
    volumes:
      - sqlite_data:/data
    # (Optional) If you have a /health endpoint:
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    #   interval: 10s
    #   retries: 5
    #   start_period: 10s

  frontend:
    image: fizzbuzzgamefrontend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      # So the user can access the backend from their browser at http://localhost:8080
      - VITE_API_BASE_URL=http://localhost:8080
    ports:
      - "4173:4173"
    depends_on:
      - backend

volumes:
  sqlite_data: