version: '3.8'

services:
  frontend:
    image: fizzbuzzgamefrontend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://localhost:8080
    ports:
      - "4173:4173"